### ISSUE TITLE
PlayerOpenSignEvent

### ISSUE THREAD

**Issue by dustinnnnnn** [mizarc/bell-claims#5]
[23:48:16] [Server thread/INFO]: [BellClaims] Enabling BellClaims v1.0
[23:48:16] [Server thread/INFO]: [BellClaims] class net.milkbowl.vault.chat.Chat
[23:48:16] [Server thread/INFO]: [BellClaims] [ACF] Enabled Asynchronous Tab Completion Support!
[23:48:16] [Server thread/ERROR]: Error occurred while enabling BellClaims v1.0 (Is it up to date?)
java.lang.NoClassDefFoundError: io/papermc/paper/event/player/PlayerOpenSignEvent
	at dev.mizarc.bellclaims.interaction.listeners.PermissionBehaviour.<clinit>(PermissionBehaviour.kt:85) ~[BellClaims-0.1.0.jar:?]
	at dev.mizarc.bellclaims.domain.permissions.ClaimPermission.<clinit>(ClaimPermission.kt:15) ~[BellClaims-0.1.0.jar:?]
	at dev.mizarc.bellclaims.interaction.listeners.ClaimInteractListener.<init>(ClaimInteractListener.kt:28) ~[BellClaims-0.1.0.jar:?]
	at dev.mizarc.bellclaims.BellClaims.registerEvents(BellClaims.kt:153) ~[BellClaims-0.1.0.jar:?]
	at dev.mizarc.bellclaims.BellClaims.onEnable(BellClaims.kt:68) ~[BellClaims-0.1.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.jar:git-Paper-17]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.jar:git-Paper-17]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:562) ~[paper-1.20.jar:git-Paper-17]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.20.jar:git-Paper-17]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.jar:git-Paper-17]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.jar:git-Paper-17]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.jar:git-Paper-17]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.jar:git-Paper-17]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.jar:git-Paper-17]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: io.papermc.paper.event.player.PlayerOpenSignEvent
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	... 17 more
[23:48:16] [Server thread/INFO]: [BellClaims] Disabling BellClaims v1.0
[23:48:16] [Server thread/INFO]: [BellClaims] Bell Claims has been Disabled

**Comment by mizarc** [comment]
Sorry for not getting back to this sooner since my hiatus from the project. Looks like it was unable to find PlayerOpenSignEvent in the API, but whatever could've happened there has likely since been resolved in newer releases as I have not encountered this issue. If you continue to encounter this in the current release of BellClaims, feel free to open up another ticket.
