### ISSUE TITLE
Unable to use latest [v0.2.5] Bell Claim on 1.21

### ISSUE THREAD

**Issue by Dyljyn** [mizarc/bell-claims#70]
## Behavior

Click on the "Create Claim" item after opening the claim menu does nothing and causes an error in the console.

```
- [Fri 12:43:51 ERROR BellClaims] Exception while handling click event in inventory 'Claim Creation', slot=4, item=BELL
java.lang.NoSuchMethodError: 'org.bukkit.craftbukkit.v1_21_R1.inventory.view.CraftAnvilView com.github.stefvanschie.inventoryframework.nms.v1_21.AnvilInventoryImpl$ContainerAnvilImpl.getBukkitView()'
    at BellClaims-0.2.5.jar//com.github.stefvanschie.inventoryframework.nms.v1_21.AnvilInventoryImpl.openInventory(AnvilInventoryImpl.java:64)
    at BellClaims-0.2.5.jar//com.github.stefvanschie.inventoryframework.gui.type.AnvilGui.show(AnvilGui.java:171)
    at BellClaims-0.2.5.jar//dev.mizarc.bellclaims.interaction.menus.ClaimManagementMenu.openClaimNamingMenu(ClaimManagementMenu.kt:126)
    at BellClaims-0.2.5.jar//dev.mizarc.bellclaims.interaction.menus.ClaimManagementMenu.openClaimNamingMenu$default(ClaimManagementMenu.kt:84)
    at BellClaims-0.2.5.jar//dev.mizarc.bellclaims.interaction.menus.ClaimManagementMenu.openClaimCreationMenu$lambda$4(ClaimManagementMenu.kt:79)
    at BellClaims-0.2.5.jar//com.github.stefvanschie.inventoryframework.gui.GuiItem.callAction(GuiItem.java:178)
    at BellClaims-0.2.5.jar//com.github.stefvanschie.inventoryframework.pane.StaticPane.click(StaticPane.java:238)
    at BellClaims-0.2.5.jar//com.github.stefvanschie.inventoryframework.gui.InventoryComponent.click(InventoryComponent.java:205)
    at BellClaims-0.2.5.jar//com.github.stefvanschie.inventoryframework.gui.type.ChestGui.click(ChestGui.java:161)
    at BellClaims-0.2.5.jar//com.github.stefvanschie.inventoryframework.gui.GuiListener.onInventoryClick(GuiListener.java:84)
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor204.execute(Unknown Source)
    at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:84)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventMan
```

## Info

Plugin version: 0.2.5
PaperMC version: 1.21 (notice: not 1.21.1)

Previous used version: 0.2.2

## Reason for issue

Though updating to 1.21.1 may fix the issue. The mod is listed on Modrinth with support for "1.21.x" which 1.21 falls under, which is/can be misleading.

**Comment by mizarc** [comment]
Can you let me know the exact PaperMC build you are using? I have tested Paper-1.21-130 with Bell Claims 0.2.5, working with full functionality.

**Comment by Dyljyn** [comment]
Definitely, it seems like it is `1.21-109-master@5a5035b`

```
This server is running Paper version 1.21-109-master@5a5035b (2024-07-23T08:16:30Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
```

**Comment by mizarc** [comment]
I have confirmed that PaperMC 1.21 builds prior to 1.21-128 do not work with the latest 0.2.5 build of Bell Claims. This is likely due to the Bukkit upstream parity with the 1.21.1 version that the IF dependency relies on to have it function with both 1.21 and 1.21.1 versions.

Is there any reason why you cannot update to a newer build? While I would like to support as many versions as possible, there would be additional complication involved in order to support builds prior to 1.21-128.

**Comment by Dyljyn** [comment]
I had some complications with other plugins during the update to 1.21.1. So I wanted to double check and also inform you regarding this bug because I wasn't able to use the latest version that "supposedly" worked with 1.21.

Thank you for the information, effort in collecting it and providing this awesome plugin. I know now how to continue from here.

**Comment by mizarc** [comment]
Thanks for letting me know! I do aim to backport the plugin to older versions when it's in a more stable position, for now I hope the support for 1.21 and subsequent minor versions can continue to be supported at least within the latest PaperMC builds as much as I can. I'll update the description to provide further information on the matter.
