### ISSUE TITLE
block place

### ISSUE THREAD

**Issue by GothkittyGirl** [mizarc/bell-claims#76]
[05:51:13 ERROR]: Could not pass event PlayerInteractEvent to BellClaims v0.3.0
java.lang.NullPointerException: null
        at BellClaims-0.3.0-1727761638711.jar/dev.mizarc.bellclaims.interaction.listeners.ClaimInteractListener.handleClaimPermission(ClaimInteractListener.kt:99) ~[BellClaims-0.3.0-1727761638711.jar:?]
        at BellClaims-0.3.0-1727761638711.jar/dev.mizarc.bellclaims.interaction.listeners.ClaimInteractListener.access$handleClaimPermission(ClaimInteractListener.kt:21) ~[BellClaims-0.3.0-1727761638711.jar:?]
        at BellClaims-0.3.0-1727761638711.jar/dev.mizarc.bellclaims.interaction.listeners.ClaimInteractListener$1.invoke(ClaimInteractListener.kt:31) ~[BellClaims-0.3.0-1727761638711.jar:?]
        at BellClaims-0.3.0-1727761638711.jar/dev.mizarc.bellclaims.interaction.listeners.ClaimInteractListener$1.invoke(ClaimInteractListener.kt:31) ~[BellClaims-0.3.0-1727761638711.jar:?]
        at BellClaims-0.3.0-1727761638711.jar/dev.mizarc.bellclaims.interaction.listeners.ClaimInteractListener.registerEvent$lambda$0(ClaimInteractListener.kt:143) ~[BellClaims-0.3.0-1727761638711.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2313-20fa61e]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2313-20fa61e]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2313-20fa61e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:604) ~[purpur-1.21.1.jar:1.21.1-2313-20fa61e]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:560) ~[purpur-1.21.1.jar:1.21.1-2313-20fa61e]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:555) ~[purpur-1.21.1.jar:1.21.1-2313-20fa61e]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:204) ~[purpur-1.21.1.jar:1.21.1-2313-20fa61e]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1934) ~[purpur-1.21.1.jar:1.21.1-2313-20fa61e]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:51) ~[purpur-1.21.1.jar:1.21.1-2313-20fa61e]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:20) ~[purpur-1.21.1.jar:1.21.1-2313-20fa61e]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.1.jar:1.21.1-2313-20fa61e]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.1.jar:1.21.1-2313-20fa61e]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.1.jar:1.21.1-2313-20fa61e]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.1.jar:1.21.1-2313-20fa61e]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1572) ~[purpur-1.21.1.jar:1.21.1-2313-20fa61e]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.1.jar:1.21.1-2313-20fa61e]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.1.jar:1.21.1-2313-20fa61e]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1549) ~[purpur-1.21.1.jar:1.21.1-2313-20fa61e]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1542) ~[purpur-1.21.1.jar:1.21.1-2313-20fa61e]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.1.jar:1.21.1-2313-20fa61e]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1501) ~[purpur-1.21.1.jar:1.21.1-2313-20fa61e]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1508) ~[purpur-1.21.1.jar:1.21.1-2313-20fa61e]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1353) ~[purpur-1.21.1.jar:1.21.1-2313-20fa61e]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2313-20fa61e]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

Version Beta v0.3.0
Purpur-1.21.1

**Comment by mizarc** [comment]
Looks like it's failing to get a valid player state for the player that's interacting with the claim. No idea how they managed to bypass the login player state creation so I can't reproduce this, but I should be able to fix it regardless.

**Comment by GothkittyGirl** [comment]
they are op as well as i have floodgate and geyer installed

**Comment by GothkittyGirl** [comment]
also there are no claims at all in the world that ik of so idk

**Comment by mizarc** [comment]
Ooh thanks for letting me know about Geyser, I wonder if that may have resulted in the player state bypass. I'll try it out for myself and see if I can reproduce the issue with it.
